services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $publicDir: "%pw.public_dir%"
      $kernel: "@kernel"
      $pageClass: "%pw.entity_page%"
      $varDir: "%kernel.project_dir%/var"
      $pageScanInterval: "%pw.pushword_page_scanner.min_interval_between_scan%"

  Pushword\PageScanner\:
    resource: "../*"
    exclude: "../{DependencyInjection,Entity,Migrations,Tests,config,Kernel.php}"

  Pushword\PageScanner\Controller\:
    resource: "../Controller/"
    tags: ["controller.service_arguments"]
