services:
  Pushword\PageScanner\PageScannerService:
    alias: pushword.page_scanner

  pushword.page_scanner:
    class: Pushword\PageScanner\PageScannerService
    autowire: true
    arguments:
      $publicDir: "%pw.public_dir%"
      $kernel: "@kernel"

  Pushword\PageScanner\PageScannerCommand:
    autowire: true
    arguments:
      $pageClass: "%pw.entity_page%"
      $varDir: "%kernel.project_dir%/var"
    tags: ["console.command"]

  Pushword\PageScanner\PageScannerController:
    autowire: true
    arguments:
      $varDir: "%kernel.project_dir%/var"
    tags:
      - { name: "controller.service_arguments" }
